language: ruby
rvm:
  - 2.0.0
script: bundle exec rake test
before_script:
  - psql -c 'create database tiny_validation_test;' -U postgres
notifications:
  email:
    on_success: never
    on_failure: change
